openapi: 3.0.0
info:
  title: TODO - API title
  description: Todo
  contact:
    name: Acme Pet Supplies
    url: "https://AcmePetSupplies.com"
    email: john.smith@acme-pet-supplies.com
  version: "1.0"
servers:
  - url: "https://localhost:8000"
tags:
  - name: TODO Tag
    description: Replace with your tag
  - name: System Health
    description: Health status of the API
paths:
  /v1/todo:
    get:
      tags:
        - TODO Tag
      summary: TODO
      operationId: todo
      description: "Todo"
      responses:
        "200":
          description: Todo
  /v1/health:
    get:
      tags:
        - System Health
      summary: Health endpoint
      operationId: health
      description: Health endpoint.
      responses:
        "200":
          description: Pass or warn response
          content:
            application/health+json:
              schema:
                $ref: "#/components/schemas/HealthyService"
              examples:
                Pass:
                  value:
                    status: pass
                    description: Health of service
                Warn:
                  value:
                    status: warn
                    description: Health of service
            application/json:
              schema:
                $ref: "#/components/schemas/HealthyService"
        "401":
          $ref: "#/components/responses/401Response"
        "403":
          $ref: "#/components/responses/403Response"
        "503":
          description: Fail response
          content:
            application/health+json:
              schema:
                $ref: "#/components/schemas/UnhealthyService"
              examples:
                Fail:
                  value:
                    status: fail
                    description: Health of service
            application/json:
              schema:
                $ref: "#/components/schemas/UnhealthyService"
components:
  responses:
    401Response:
      description: Unauthorized
      content:
        application/json:
          schema:
            title: 401 Error
            type: object
            additionalProperties: false
            properties:
              message:
                type: string
                pattern: ^[\w\s\.\"\']+$
                description: Invalid authentication credentials.
                minLength: 1
                maxLength: 100
                example: Invalid authentication credentials.
            required:
              - message
    403Response:
      description: Forbidden
      content:
        application/json:
          schema:
            title: 403 Error
            type: object
            additionalProperties: false
            properties:
              message:
                type: string
                pattern: ^[\w\s\.\"\']+$
                description: Forbidden.
                minLength: 1
                maxLength: 100
                example: Forbidden.
            required:
              - message
  schemas:
    HealthyService:
      title: Health
      type: object
      additionalProperties: false
      properties:
        status:
          enum:
            - pass
            - warn
          example: pass
          type: string
          description: Indicates whether the service status is acceptable or not.
        description:
          type: string
          description: Human-friendly description of the service.
          pattern: ^[\w\s\.\"\']+$
          minLength: 1
          maxLength: 100
          example: Health of service
      required:
        - status
    UnhealthyService:
      title: Health
      type: object
      additionalProperties: false
      properties:
        status:
          enum:
            - fail
          example: fail
          type: string
          description: Indicates whether the service status is acceptable or not.
        description:
          type: string
          description: Human-friendly description of the service.
          pattern: ^[\w\s\.\"\']+$
          minLength: 1
          maxLength: 100
          example: Health of service
      required:
        - status
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-API-Key
      in: header

security:
  - apiKey: []
